stages:
  data_ingestion:
    cmd: python src/chest_cancer/pipeline/stage1_data_ingestion.py
    deps:
      - src/chest_cancer/pipeline/stage1_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/chest-cancer-ct

  data_preprocessing:
    cmd: python src/chest_cancer/pipeline/stage2_base_model.py
    deps:
      - src/chest_cancer/pipeline/stage2_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/model_selection

  model_training:
    cmd: python src/chest_cancer/pipeline/stage3_model_training.py
    deps:
      - src/chest_cancer/pipeline/stage3_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/chest-cancer-ct
      - artifacts/model_selection
    params:
      - BATCH_SIZE
      - EPOCHS
      - AUGMENTATION
    outs:
      - artifacts/model_training/model.keras

  model_evaluation:
    cmd: python src/chest_cancer/pipeline/stage4_model_evaluation.py
    deps:
      - src/chest_cancer/pipeline/stage4_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/chest-cancer-ct
      - artifacts/model_training/model.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false
